server:
port: 8080

spring:
  datasource:
    username: root
    password: "!Ujhtkrf67"
    url: jdbc:mysql://localhost:3306/lemma?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

# example values
settings:
  webinterfacelogin: user
  webinterfacepassword: 123
  prefix: search_
  agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  webinterface: /admin
indexing-settings:
  sites:
    - url: http://www.playback.ru/
      name: Playback
    - url: https://et-cetera.ru/mobile/
      name: Theatre
 